### ISSUE TITLE
[Publications/Create] solo sugerencia de un Botón en la publicación

### ISSUE THREAD

**Issue by mgiquiar** [maxenz/trocar#10]
En el ultimo paso para crear una publicación el botón dice "finalizar Publicación", a mi me parece que da para confusiones, yo lo llamaría "Publicar" o "Listo, Publicar!"
que les parece?

**Comment by christian-pereyra** [comment]
Listo!
![image](https://user-images.githubusercontent.com/51100358/66017150-f4dc5180-e4af-11e9-917c-3379b3bd29a6.png)
