### ISSUE TITLE
[MyFavourites]Problemas al Quitar publicaciones de Favoritos

### ISSUE THREAD

**Issue by mgiquiar** [maxenz/trocar#11]
Cuando se quita una publicación de favoritos y se refresca el listado , la misma vuelve a aparecer, adjunto capturas. también aparece repetida

![cap1_inicio](https://user-images.githubusercontent.com/28371665/65898477-062a3e80-e388-11e9-99f0-0f4480d05441.png)
![cap2_favoritos](https://user-images.githubusercontent.com/28371665/65898479-062a3e80-e388-11e9-86bf-07d84aab1fb3.png)
![cap3_favoritos_quitado](https://user-images.githubusercontent.com/28371665/65898480-06c2d500-e388-11e9-8793-c0aa4ffd3850.png)
![cap4_favoritos_vuelve_a_aparecer](https://user-images.githubusercontent.com/28371665/65898481-075b6b80-e388-11e9-8801-722e1096f67a.png)

**Comment by maxenz** [comment]
repetido de #14
