### ISSUE TITLE
[MyFavourites] La misma publicación se está recuperando múltiples veces

### ISSUE THREAD

**Issue by christian-pereyra** [maxenz/trocar#14]
### Pasos para reproducir:
1. Ir a Mis Favoritos habiendo marcado antes alguna publicación como favorita (quizás tenga que ser una publicación propia)

### Resultado Esperado:
- Se muestra una lista de publicaciones favoritas
- Cada publicación aparece solamente una vez

### Resultado Obtenido:
- Se muestra una lista de publicaciones favoritas
- Algunas publicaciones aparecen más de una vez

### Notas:
Mis Favoritos:
`[{"publication":{"user":{"username":"maximilianopoggio","email":"maximilianopoggio@gmail.com","token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1ETXpRalJHUkRrMk5UVXpORUpET1RrNE9VSXdPRFUyUVVNME9UYzFRVEl6TmpNME1qaEZSUSJ9.eyJuaWNrbmFtZSI6Im1heGltaWxpYW5vcG9nZ2lvIiwibmFtZSI6Im1heGltaWxpYW5vcG9nZ2lvQGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3MuZ3JhdmF0YXIuY29tL2F2YXRhci80Nzc5NWI0NGFjMzYyODUzOGQ1NDdmY2I0M2Q5MTRjZD9zPTQ4MCZyPXBnJmQ9aHR0cHMlM0ElMkYlMkZjZG4uYXV0aDAuY29tJTJGYXZhdGFycyUyRm1hLnBuZyIsInVwZGF0ZWRfYXQiOiIyMDE5LTA5LTMwVDAyOjQ2OjIxLjMxMFoiLCJpc3MiOiJodHRwczovL21wb2dnaW8uYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDVkMTBlM2VkYzAwZTZkMGRlYWZlOWQ3NSIsImF1ZCI6InQ0ekNQWmNyR2V0OGhWNGhwUUdWRmRJUVpTMEFpVlQxIiwiaWF0IjoxNTY5ODExNTgxLCJleHAiOjE1Njk4NDc1ODEsIm5vbmNlIjoieW9lbDdhUDBTdm1tTEZYQU56MkVUYnlKdi0xRmNlalYifQ.wljyZoUYr-kTL7yZylPY8AsWak-LwoXFkjZwc7_8KWhSY_tWe7LB8zSKJHqcv-5aZ79h7Mhcm2LbYvspiOorINv6B6gxBsAdvXKgHPztpTQwNKToDqu7uCNF4-NSJborr5L0q8PbRwNhSSiYo8hTgC3NiYukN0a1JVjzVnShjXdiE8MVZYI3xLbnlw4X_NSgTItcq0x8hiLyh9zLzybdba7C0kpxWoA4oEBYlpHaPSRuJMUzq9bqPTKEGha4xRVmKM8SNrh72sGNmbjjlpdSgDwLpLGSOuxmjqTPsPmurnTlI0ta1FpCQVaUOZO3zVKRzLvRef63E2SLDAHV56na3A","id":1,"createdDate":"2019-09-30T02:37:39.328Z","updatedDate":"2019-09-30T02:46:23.000Z","firstName":null,"lastName":null},"category":{"name":"comida","description":"comida","id":1,"createdDate":"2019-09-30T02:37:30.567Z","updatedDate":"2019-09-30T02:37:30.567Z"},"status":null,"title":"esta es una publicacion falopa","description":"falopaaaa","imageUrl":"superurl","id":1,"createdDate":"2019-09-30T02:38:09.947Z","updatedDate":"2019-09-30T02:38:09.947Z"},"id":1,"createdDate":"2019-09-30T02:51:11.697Z","updatedDate":"2019-09-30T02:51:11.697Z"},{"publication":{"user":{"username":"pereyra.christian.h","email":"pereyra.christian.h@gmail.com","token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1ETXpRalJHUkRrMk5UVXpORUpET1RrNE9VSXdPRFUyUVVNME9UYzFRVEl6TmpNME1qaEZSUSJ9.eyJuaWNrbmFtZSI6InBlcmV5cmEuY2hyaXN0aWFuLmgiLCJuYW1lIjoicGVyZXlyYS5jaHJpc3RpYW4uaEBnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zLmdyYXZhdGFyLmNvbS9hdmF0YXIvYTAzMmFhMmJlMjMzNzQ3NGZiMjg1ZDVjZWNlOGRkNjY_cz00ODAmcj1wZyZkPWh0dHBzJTNBJTJGJTJGY2RuLmF1dGgwLmNvbSUyRmF2YXRhcnMlMkZwZS5wbmciLCJ1cGRhdGVkX2F0IjoiMjAxOS0wOS0zMFQyMzowODo0Ny4xNzdaIiwiaXNzIjoiaHR0cHM6Ly9tcG9nZ2lvLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1Y2VlMTViNDdlZWQ5MTExMDU5NDk1YTQiLCJhdWQiOiJ0NHpDUFpjckdldDhoVjRocFFHVkZkSVFaUzBBaVZUMSIsImlhdCI6MTU2OTg4NDkyNywiZXhwIjoxNTY5OTIwOTI3LCJub25jZSI6InA1Qlo0QmhSZlFkN1BfNDVvckNYTkhmRG5xaUxSWG5aIn0.Cq-Zc-EiT9d77KEfobTHQIw5vy0ELNSZg6JxZ3yevutVdsITx34s-C5ZT85iT0tCVrfyWBkUKens8TjYhIGMR0bhJVKwhKsziKy3tn4RDZ_s9dk03030OxLfQ7yQ7G2XeRMhwb-6TlI7fhfMIiMNwx_wy9gWyyASbD_7ppAR8-yeWd8VWph5ubBpYA0Gvbf2rsMdOwq4DpaoXX45qN1rXDTIJMEKsuzGgCSMdS3XlVWwFpMv4pMzOV9HX_HZkTPJSiJyN9LyALkIhfKFYvDoOZu_7q2HRDkBQGSIkDy-bO4n3RLWmVsflZJejswfUtVG3vQXFP0NSzSutZmGdKipNw","id":3,"createdDate":"2019-09-30T02:39:28.997Z","updatedDate":"2019-09-30T23:08:49.000Z","firstName":null,"lastName":null},"category":{"name":"comida","description":"comida","id":1,"createdDate":"2019-09-30T02:37:30.567Z","updatedDate":"2019-09-30T02:37:30.567Z"},"status":null,"title":"Empanadas x12","description":"Empanadas x12","imageUrl":"superurl","id":2,"createdDate":"2019-09-30T12:39:51.281Z","updatedDate":"2019-09-30T12:39:51.281Z"},"id":2,"createdDate":"2019-09-30T12:40:14.337Z","updatedDate":"2019-09-30T12:40:14.337Z"},{"publication":{"user":{"username":"pereyra.christian.h","email":"pereyra.christian.h@gmail.com","token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1ETXpRalJHUkRrMk5UVXpORUpET1RrNE9VSXdPRFUyUVVNME9UYzFRVEl6TmpNME1qaEZSUSJ9.eyJuaWNrbmFtZSI6InBlcmV5cmEuY2hyaXN0aWFuLmgiLCJuYW1lIjoicGVyZXlyYS5jaHJpc3RpYW4uaEBnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zLmdyYXZhdGFyLmNvbS9hdmF0YXIvYTAzMmFhMmJlMjMzNzQ3NGZiMjg1ZDVjZWNlOGRkNjY_cz00ODAmcj1wZyZkPWh0dHBzJTNBJTJGJTJGY2RuLmF1dGgwLmNvbSUyRmF2YXRhcnMlMkZwZS5wbmciLCJ1cGRhdGVkX2F0IjoiMjAxOS0wOS0zMFQyMzowODo0Ny4xNzdaIiwiaXNzIjoiaHR0cHM6Ly9tcG9nZ2lvLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1Y2VlMTViNDdlZWQ5MTExMDU5NDk1YTQiLCJhdWQiOiJ0NHpDUFpjckdldDhoVjRocFFHVkZkSVFaUzBBaVZUMSIsImlhdCI6MTU2OTg4NDkyNywiZXhwIjoxNTY5OTIwOTI3LCJub25jZSI6InA1Qlo0QmhSZlFkN1BfNDVvckNYTkhmRG5xaUxSWG5aIn0.Cq-Zc-EiT9d77KEfobTHQIw5vy0ELNSZg6JxZ3yevutVdsITx34s-C5ZT85iT0tCVrfyWBkUKens8TjYhIGMR0bhJVKwhKsziKy3tn4RDZ_s9dk03030OxLfQ7yQ7G2XeRMhwb-6TlI7fhfMIiMNwx_wy9gWyyASbD_7ppAR8-yeWd8VWph5ubBpYA0Gvbf2rsMdOwq4DpaoXX45qN1rXDTIJMEKsuzGgCSMdS3XlVWwFpMv4pMzOV9HX_HZkTPJSiJyN9LyALkIhfKFYvDoOZu_7q2HRDkBQGSIkDy-bO4n3RLWmVsflZJejswfUtVG3vQXFP0NSzSutZmGdKipNw","id":3,"createdDate":"2019-09-30T02:39:28.997Z","updatedDate":"2019-09-30T23:08:49.000Z","firstName":null,"lastName":null},"category":{"name":"comida","description":"comida","id":1,"createdDate":"2019-09-30T02:37:30.567Z","updatedDate":"2019-09-30T02:37:30.567Z"},"status":null,"title":"Empanadas x12","description":"Empanadas x12","imageUrl":"superurl","id":2,"createdDate":"2019-09-30T12:39:51.281Z","updatedDate":"2019-09-30T12:39:51.281Z"},"id":3,"createdDate":"2019-09-30T12:49:59.195Z","updatedDate":"2019-09-30T12:49:59.195Z"},{"publication":{"user":{"username":"pereyra.christian.h","email":"pereyra.christian.h@gmail.com","token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1ETXpRalJHUkRrMk5UVXpORUpET1RrNE9VSXdPRFUyUVVNME9UYzFRVEl6TmpNME1qaEZSUSJ9.eyJuaWNrbmFtZSI6InBlcmV5cmEuY2hyaXN0aWFuLmgiLCJuYW1lIjoicGVyZXlyYS5jaHJpc3RpYW4uaEBnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zLmdyYXZhdGFyLmNvbS9hdmF0YXIvYTAzMmFhMmJlMjMzNzQ3NGZiMjg1ZDVjZWNlOGRkNjY_cz00ODAmcj1wZyZkPWh0dHBzJTNBJTJGJTJGY2RuLmF1dGgwLmNvbSUyRmF2YXRhcnMlMkZwZS5wbmciLCJ1cGRhdGVkX2F0IjoiMjAxOS0wOS0zMFQyMzowODo0Ny4xNzdaIiwiaXNzIjoiaHR0cHM6Ly9tcG9nZ2lvLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1Y2VlMTViNDdlZWQ5MTExMDU5NDk1YTQiLCJhdWQiOiJ0NHpDUFpjckdldDhoVjRocFFHVkZkSVFaUzBBaVZUMSIsImlhdCI6MTU2OTg4NDkyNywiZXhwIjoxNTY5OTIwOTI3LCJub25jZSI6InA1Qlo0QmhSZlFkN1BfNDVvckNYTkhmRG5xaUxSWG5aIn0.Cq-Zc-EiT9d77KEfobTHQIw5vy0ELNSZg6JxZ3yevutVdsITx34s-C5ZT85iT0tCVrfyWBkUKens8TjYhIGMR0bhJVKwhKsziKy3tn4RDZ_s9dk03030OxLfQ7yQ7G2XeRMhwb-6TlI7fhfMIiMNwx_wy9gWyyASbD_7ppAR8-yeWd8VWph5ubBpYA0Gvbf2rsMdOwq4DpaoXX45qN1rXDTIJMEKsuzGgCSMdS3XlVWwFpMv4pMzOV9HX_HZkTPJSiJyN9LyALkIhfKFYvDoOZu_7q2HRDkBQGSIkDy-bO4n3RLWmVsflZJejswfUtVG3vQXFP0NSzSutZmGdKipNw","id":3,"createdDate":"2019-09-30T02:39:28.997Z","updatedDate":"2019-09-30T23:08:49.000Z","firstName":null,"lastName":null},"category":{"name":"comida","description":"comida","id":1,"createdDate":"2019-09-30T02:37:30.567Z","updatedDate":"2019-09-30T02:37:30.567Z"},"status":null,"title":"Empanadas x12","description":"Empanadas x12","imageUrl":"superurl","id":2,"createdDate":"2019-09-30T12:39:51.281Z","updatedDate":"2019-09-30T12:39:51.281Z"},"id":13,"createdDate":"2019-09-30T16:43:56.846Z","updatedDate":"2019-09-30T16:43:56.846Z"}]`

**Comment by Juancitodj** [comment]
Ya esta ok este, no me deja cerrarlo
